name: pdf_text_extraction
description: pdf_text_extraction
version: 1.2.0
homepage: https://github.com/insinfo/pdf_text_extraction
#repository: https://github.com/insinfo/pdf_text_extraction

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  
dev_dependencies: 
  build_runner: ^2.4.12
  ffigen: ^14.0.1
  #for test only
  http: ^1.2.2
  postgres: ^3.3.0
  intl: ^0.19.0
  html: ^0.15.4
  pdfium_bindings: ^2.0.1
#dart run ffigen --config ffigen.yaml